#ifndef __WADDELZGUI_H
#define __WADDELZGUI_H

#include "Button.h"
#include "Checkbutton.h"
#include "ColorPicker.h"
#include "ComboBox.h"
#include "Container.h"
#include "ContextMenu.h"
#include "CrashHandler.h"
#include "Cursor.h"
#include "CustomItem.h"
#include "DatePicker.h"
#include "Element.h"
#include "ElementDefines.h"
#include "FileDialogs.h"
#include "Fonts.h"
#include "gui_resource.h"
#include "Icon.h"
#include "ImageList.h"
#include "Keyboard.h"
#include "Label.h"
#include "ListBox.h"
#include "ListView.h"
#include "LoadingBar.h"
#include "Menu.h"
#include "Paint.h"
#include "PropertyPage.h"
#include "RichEdit.h"
#include "Screen.h"
#include "ScrollWheel.h"
#include "Slider.h"
#include "StatusBar.h"
#include "SubDialog.h"
#include "TabController.h"
#include "TextEntry.h"
#include "ToolTip.h"
#include "ToolBar.h"
#include "TreeView.h"
#include "Window.h"

#pragma once

#endif